apiVersion: v1
kind: Service
metadata:
  name: pkmallia
spec:
  selector:
    app: pkmallia
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkmallia
  labels:
    app: pkmallia
spec:
  selector:
    matchLabels:
      app: pkmallia
  replicas: 3
  template:
    metadata:
      labels:
        app: pkmallia
    spec:
      containers:
      - name: pkmallia
        image: pkmallia/firstimage:latest
        ports:
        - containerPort: 5000
