
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkmallia
  labels:
    app: fashion
spec:
  selector:
    matchLabels:
      app: fashion
  replicas: 1
  template:
    metadata:
      labels:
        app: fashion
    spec:
      containers:
      - name: pkmallia
        image: pkmallia/firstimage:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
  labels:
    app: fashion
spec:
  selector:
    app: fashion
  ports:
  - name: nodeporttest
    port: 80
    targetPort: 80
    nodePort: 30007
    protocol: TCP
  type: NodePort
---
