apiVersion: v1
kind: Service
metadata:
  name: pkmallia
spec:
  selector:
    app: pkmallia
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkmallia
  labels:
    app: pkmallia
spec:
  selector:
    matchLabels:
      app: pkmallia
  replicas: 1
  template:
    metadata:
      labels:
        app: pkmallia
    spec:
      containers:
      - name: pkmallia
        image: https://hub.docker.com/repository/docker/pkmallia/firstimage:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
